updated functions to use common entry and package; added emulator sup…
chalkclassroom/CoachingApp pull request #253
Opened 2020-10-21 00:38 UTC by thompchr

…port for local execution

added firebase init command and firestore emulator

added back local dev switches

2020-10-22 19:20 UTC, clarah2 requested changes

2020-10-22 19:20 UTC, clarah2 commented on functions/index.js
> +exports.funcTransitionTypeSummary = require('./funcTransitionTypeSummary').funcTransitionTypeSummary;
missing a few!

2020-11-05 18:05 UTC, clarah2 submitted a review, later dismissed
funcTeacherMathSummary has not been updated in GCP...the last deployed version was from April. Everything else looks good.

2020-11-05 18:26 UTC, clarah2 submitted a review, later dismissed
awesome!

2020-11-24 03:03 UTC, thompchr commented
Ok, rebased off of the latest changes. @clarah2 if you're good with this, you can merge once you submit a review!

2020-11-24 16:23 UTC, clarah2 approved these changes

2020-11-24 16:23 UTC, merged